const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-ET',{style:'currency',currency:'ETB',maximumFractionDigits:0}).format(n);
const logo=()=>`<span class="logo" aria-label="Biloo"><span class="mark"></span><span class="wordmark">BILOO</span></span>`;
const icon=n=>({home:'⌂',explore:'◇',notifications:'◌',profile:'○',cart:'▱',heart:'♡'}[n]||'·');
const P=[
 ['p1','TOTEME','Signature Wool Wrap Coat',12800,16000,'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&w=900&q=84',['XS','S','M','L'],'M','#C8B189'],
 ['p2','AERON','Fluid Tailored Trousers',7200,8900,'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=84',['S','M','L','XL'],'M','#222'],
 ['p3','STUDIO NICHOLSON','Soft Structure Overshirt',8600,0,'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=900&q=84',['XS','S','M','L','XL'],'L','#DED7C8'],
 ['p4','LEMAIRE','Draped Everyday Shirt',6900,7600,'https://images.unsplash.com/photo-1608234807905-4466023792f5?auto=format&fit=crop&w=900&q=84',['S','M','L'],'M','#F1EEE5'],
 ['p5','OUR LEGACY','Relaxed Black Denim',8100,0,'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=84',['28','30','32','34','36'],'32','#171717'],
 ['p6','ARKET','Fine Merino Crew Knit',5200,6500,'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=84',['XS','S','M','L','XL'],'M','#A49F94'],
].map(x=>({id:x[0],brand:x[1],name:x[2],price:x[3],old:x[4],img:x[5],sizes:x[6],match:x[7],color:x[8],rating:4.8,reviews:84}));
const cats=[['Women','https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=300&q=80'],['Men','https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=300&q=80'],['Teens','https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80'],['Kids','https://images.unsplash.com/photo-1503919005314-30d93d07d823?auto=format&fit=crop&w=300&q=80']];
const base={started:false,auth:false,tab:'home',wish:[],cart:{},sizes:{},measure:{height:'172',chest:'94',waist:'81',hip:'96',inseam:'79'},notes:[['Your next-day edit is ready','Six pieces match your fit profile and can arrive tomorrow.'],['Saved piece back in your size','The Soft Structure Overshirt is available again in L.']]};
let S={...base,...JSON.parse(localStorage.getItem('biloo-state')||'{}')}, query=''; const save=()=>localStorage.setItem('biloo-state',JSON.stringify(S));
const qty=()=>Object.values(S.cart).reduce((a,b)=>a+b,0), total=()=>Object.entries(S.cart).reduce((a,[id,q])=>a+P.find(p=>p.id===id).price*q,0);
const toast=t=>{ $('#toast-root').innerHTML=`<div class="toast">${t}</div>`;setTimeout(()=>$('#toast-root').innerHTML='',1800)}; const ok=()=>{navigator.vibrate?.(10)};
const top=()=>`<header class="topbar">${logo()}<button class="icon-btn cart-wrap" data-cart aria-label="Cart">${icon('cart')}${qty()?`<span class="badge">${qty()}</span>`:''}</button></header>`;
const nav=()=>`<nav class="bottomnav">${['home','explore','notifications','profile'].map(n=>`<button class="navitem ${S.tab===n?'active':''}" data-tab="${n}"><b>${icon(n)}</b><span>${n==='notifications'?'Notification':n[0].toUpperCase()+n.slice(1)}</span></button>`).join('')}</nav>`;
function card(p){let w=S.wish.includes(p.id);return`<article class="product-card" data-product="${p.id}" tabindex="0"><div class="product-image"><img src="${p.img}" alt="${p.name}" loading="lazy"><button class="icon-btn heart" data-wish="${p.id}" aria-label="Save piece">${w?'♥':'♡'}</button></div><div class="product-meta"><div class="brand">${p.brand}</div><div class="rating">★ ${p.rating} · ${p.reviews}</div><h3>${p.name}</h3><div class="price">${money(p.price)}${p.old?`<span class="strike">${money(p.old)}</span>`:''}</div></div></article>`}
function splash(){return`<main class="splash"><div class="splash-bg"></div><div class="splash-content"><div class="splash-logo">${logo()}</div><h1 class="display-xl">WEAR THE MOMENT</h1><p class="body-l">Curated edits, matched to your size, delivered by tomorrow.</p><button class="btn btn-light" style="width:100%" data-start>Get Started</button></div></main>`}
function auth(){return`<main class="auth"><section class="auth-card">${logo()}<h1 class="title">Welcome Back</h1><p class="body charcoal">Sign in to pick up your edit, track orders and keep your saved pieces in one place.</p><form id="login"><div class="field"><label>Email or username</label><input id="email" value="demo@biloo.app"></div><div class="field"><label>Password</label><input id="password" type="password" value="biloo123"><button type="button" class="icon-btn trail" data-eye>◉</button></div><div id="auth-error" class="error-text"></div><button class="btn btn-primary" style="width:100%;margin-top:12px">Login</button><div class="auth-alt"><button class="btn btn-secondary" type="button" data-demo>Continue with Google</button><button class="btn btn-secondary" type="button" data-demo>Continue with Apple</button></div><div class="auth-link">Don't have an account? <button class="link-btn" type="button" data-demo>Register here</button></div></form></section></main>`}
function home(){return`<div class="shell"><div class="screen">${top()}${!navigator.onLine?'<div class="offline">Offline · showing saved and recently viewed pieces</div>':''}<section class="hero"><img src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1400&q=84" alt="Biloo editorial"><div class="hero-copy"><div class="eyebrow">NEW COLLECTIONS</div><h2 class="display">20% OFF</h2><button class="pill-light" data-go="explore">SHOP NOW</button></div></section><section class="section"><div class="section-head gutter"><h2 class="title">Shop by Category</h2><button class="link-btn" data-go="explore">See All</button></div><div class="rail">${cats.map(c=>`<button class="category link-btn" data-search="${c[0]}"><img src="${c[1]}" alt="${c[0]}"><span>${c[0]}</span></button>`).join('')}</div></section><section class="section"><div class="section-head gutter"><h2 class="title">Curated For You</h2><button class="link-btn" data-go="explore">See All</button></div><div class="rail">${P.map(card).join('')}</div></section><article class="editorial"><div class="eyebrow muted">THE EDIT OF THE WEEK</div><img src="https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=84" alt="Editorial"><h2 class="title">Soft structure. Clear intent.</h2><p>A restrained edit chosen to work together.</p></article></div>${nav()}</div>`}
function explore(){let r=query?P.filter(p=>(p.brand+' '+p.name).toLowerCase().includes(query.toLowerCase())):P;return`<div class="shell"><div class="screen">${top()}<div class="page-title"><div class="eyebrow muted">DISCOVER</div><h1 class="display">Explore</h1></div><div class="search-wrap"><label class="search">⌕<input id="search" value="${query}" placeholder="Search pieces and brands"></label></div>${r.length?`<div class="search-results">${r.map(card).join('')}</div>`:`<div class="empty"><h2 class="title">Nothing exact for “${query}”</h2><p>Try tailoring, knitwear or relaxed essentials.</p></div>`}<div style="height:120px"></div></div>${nav()}</div>`}
function notes(){return`<div class="shell"><div class="screen">${top()}<div class="page-title"><h1 class="display">Notifications</h1></div><div class="group-title eyebrow muted">TODAY</div>${S.notes.map((n,i)=>`<article class="notice-row ${n[2]?'read':''}" data-note="${i}"><span class="notice-dot"></span><div><p class="label">${n[0]}</p><p class="body charcoal">${n[1]}</p><time>${i?'2 hr':'18 min'}</time></div></article>`).join('')}<div class="gutter" style="margin-top:32px"><button class="btn btn-secondary" style="width:100%" data-notify>Allow order updates</button></div></div>${nav()}</div>`}
function profile(){return`<div class="shell"><div class="screen">${top()}<div class="page-title"><div class="eyebrow muted">YOUR BILOO</div><h1 class="display">Mahir</h1><div class="body charcoal">View and edit account</div></div><div class="profile-group">${[['Orders','Recent delivery · tomorrow'],['Saved Pieces',`${S.wish.length} saved`],['Style Preferences','Quiet tailoring · neutral'],['Measurement Profile','Completed'],['Addresses','Addis Ababa'],['Payments','Demo mode']].map((r,i)=>`<button class="profile-row link-btn" data-profile="${i}"><span>${r[0]}</span><span>${r[1]} ›</span></button>`).join('')}</div><div class="gutter"><button class="btn btn-secondary" style="width:100%" data-theme>Toggle dark preview</button><button class="btn btn-secondary" style="width:100%;margin-top:10px" data-signout>Sign out</button></div></div>${nav()}</div>`}
function render(){let a=$('#app');a.innerHTML=!S.started?splash():!S.auth?auth():S.tab==='home'?home():S.tab==='explore'?explore():S.tab==='notifications'?notes():profile();bind()}
function sheet(html){let d=document.createElement('div');d.className='sheet-backdrop';d.innerHTML=`<section class="sheet max" role="dialog" aria-modal="true"><div class="grab"></div>${html}</section>`;document.body.append(d);d.onclick=e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()};return d}
function product(id){let p=P.find(x=>x.id===id),sel=S.sizes[id]||p.match;sheet(`<div class="sheet-head"><h2 class="title">${p.brand}</h2><button class="icon-btn" data-close>×</button></div><div class="detail-gallery"><img src="${p.img}" alt="${p.name}"></div><div class="detail-info"><div class="label muted">${p.brand} · ★ ${p.rating}</div><h1 class="title">${p.name}</h1><div class="price">${money(p.price)} ${p.old?`<span class="strike">${money(p.old)}</span>`:''}</div><p class="desc">An intentionally cut piece with a soft hand and controlled drape.</p><div class="label">Colour</div><div class="swatches"><button class="swatch active"><span style="background:${p.color}"></span></button></div><div class="label" style="margin-top:28px">Size</div><div class="sizes">${p.sizes.map(s=>`<button class="size ${s===sel?'active':''}" data-size="${id}|${s}">${s}</button>`).join('')}</div><div class="fit-badge">Size ${p.match} · matched to your profile</div><div style="margin-top:32px"><strong>Delivery tomorrow</strong><div class="muted">Order before 9:00 PM Addis Ababa time</div></div></div><div class="sticky-actions"><div class="btn-row"><button class="btn btn-secondary" data-add="${id}">ADD TO CART</button><button class="btn btn-primary" data-buy="${id}">BUY NOW</button></div></div>`);bind()}
function cart(){
 let entries=Object.entries(S.cart).filter(x=>x[1]);
 let body='';
 if(entries.length){
   body=entries.map(([id,q])=>{let p=P.find(x=>x.id===id);return `<article class="cart-row"><img src="${p.img}" alt="${p.name}"><div><div class="micro muted">${p.brand}</div><h3>${p.name}</h3><div class="body muted">${S.sizes[id]||p.match} · Selected colour</div><div class="body">Delivery tomorrow</div><div class="qty"><button data-qty="${id}|-1">−</button><span>${q}</span><button data-qty="${id}|1">+</button><strong style="margin-left:auto">${money(p.price*q)}</strong></div></div></article>`}).join('');
   body+=`<div class="summary"><div class="summary-line total"><span>Total</span><span>${money(total())}</span></div><button class="btn btn-primary" style="width:100%" data-checkout>CHECKOUT</button></div>`;
 } else body='<div class="empty"><h2 class="title">Your cart is clear</h2><p>Saved pieces and your current edit are still waiting.</p></div>';
 sheet(`<div class="sheet-head"><h2 class="title">Your Cart</h2><button class="icon-btn" data-close>×</button></div>${body}`);bind();
}
function checkout(){sheet(`<div class="sheet-head"><h2 class="title">Checkout</h2><button class="icon-btn" data-close>×</button></div><form id="checkout"><div class="checkout-section"><h3>Delivery address</h3><div class="field"><label>Name</label><input required value="Mahir"></div><div class="field"><label>Phone · +251</label><input required value="912345678"></div><div class="field"><label>City</label><input required value="Addis Ababa"></div><div class="field"><label>Area</label><input required value="Bole"></div></div><div class="checkout-section"><h3>Pay</h3><div class="pay-options"><button type="button" class="pay-card" data-pay>Apple Pay</button><button type="button" class="pay-card" data-pay>Google Pay</button></div><div class="field"><label>Card · demo</label><input value="4242 4242 4242 4242"></div></div><div class="summary-line total"><span>Total</span><span>${money(total())}</span></div><button class="btn btn-primary" style="width:100%;margin-top:20px">PLACE ORDER</button></form>`);bind()}
function fit(){let m=S.measure;sheet(`<div class="sheet-head"><h2 class="title">Size & Fit Profile</h2><button class="icon-btn" data-close>×</button></div><h1 class="display">Fit that starts with you</h1><p class="privacy">Camera is requested only after you choose guided scan. This browser demo never uploads the camera stream.</p><div class="measure-grid">${Object.entries(m).map(([k,v])=>`<div class="field"><label>${k} · cm</label><input data-measure="${k}" value="${v}"></div>`).join('')}</div><button class="btn btn-secondary" style="width:100%" data-camera>Use guided scan</button><button class="btn btn-primary" style="width:100%;margin-top:10px" data-save-fit>Save profile</button>`);bind()}
async function camera(){let h=sheet(`<div class="sheet-head"><h2 class="title">Guided fit scan</h2><button class="icon-btn" data-close>×</button></div><p>Stand naturally and keep your full body in frame.</p><div class="camera"><video autoplay playsinline muted></video><div class="camera-guide"></div></div><button class="btn btn-primary" style="width:100%;margin-top:16px" data-close>Measurements ready</button>`);try{$('video',h).srcObject=await navigator.mediaDevices.getUserMedia({video:true})}catch{h.remove();toast('Camera access is off. Manual measurements remain available.')};bind()}
function bind(){
 $$('[data-start]').forEach(b=>b.onclick=()=>{S.started=true;save();render()}); $$('[data-demo]').forEach(b=>b.onclick=()=>{S.auth=true;save();ok();render()});
 let l=$('#login');if(l)l.onsubmit=e=>{e.preventDefault();if(!$('#email').value.includes('@'))return $('#auth-error').textContent='Enter a valid email address.';S.auth=true;save();ok();render()}; let eye=$('[data-eye]');if(eye)eye.onclick=()=>{$('#password').type=$('#password').type==='password'?'text':'password'};
 $$('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;save();render()});$$('[data-go]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.go;save();render()});$$('[data-search]').forEach(b=>b.onclick=()=>{query=b.dataset.search;S.tab='explore';render()});
 $$('[data-product]').forEach(b=>b.onclick=e=>{if(!e.target.closest('[data-wish]'))product(b.dataset.product)});$$('[data-wish]').forEach(b=>b.onclick=e=>{e.stopPropagation();let id=b.dataset.wish;S.wish=S.wish.includes(id)?S.wish.filter(x=>x!==id):[...S.wish,id];save();ok();render();toast('Saved pieces updated')});
 $$('[data-cart]').forEach(b=>b.onclick=cart);$$('[data-size]').forEach(b=>b.onclick=()=>{let[id,s]=b.dataset.size.split('|');S.sizes[id]=s;save();ok();b.parentElement.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
 $$('[data-add]').forEach(b=>b.onclick=()=>{let id=b.dataset.add;S.cart[id]=(S.cart[id]||0)+1;save();ok();b.textContent='ADDED';toast('Added to cart')});$$('[data-buy]').forEach(b=>b.onclick=()=>{let id=b.dataset.buy;S.cart[id]=Math.max(1,S.cart[id]||0);save();$('.sheet-backdrop')?.remove();checkout()});
 $$('[data-qty]').forEach(b=>b.onclick=()=>{let[id,d]=b.dataset.qty.split('|');S.cart[id]=Math.max(0,(S.cart[id]||0)+Number(d));save();$('.sheet-backdrop')?.remove();cart()});$$('[data-checkout]').forEach(b=>b.onclick=()=>{$('.sheet-backdrop')?.remove();checkout()});$$('[data-pay]').forEach(b=>b.onclick=()=>{ok();toast(`${b.textContent} selected for demo checkout`)});
 let c=$('#checkout');if(c)c.onsubmit=e=>{e.preventDefault();if(!navigator.onLine)return toast("You're offline. Checkout details stay on this device.");S.cart={};S.notes.unshift(['Order placed','Your Biloo edit is expected tomorrow.',true]);save();ok();$('.sheet-backdrop')?.remove();sheet(`<div class="empty"><h2 class="display">Order placed</h2><p>Delivery expected tomorrow. No money was charged in this demo.</p><button class="btn btn-primary" data-close>Continue</button></div>`);bind()};
 let s=$('#search');if(s){let t;s.oninput=()=>{clearTimeout(t);t=setTimeout(()=>{query=s.value;render();requestAnimationFrame(()=>$('#search')?.focus())},180)}}
 $$('[data-note]').forEach(b=>b.onclick=()=>{S.notes[b.dataset.note][2]=true;save();render()});$$('[data-notify]').forEach(b=>b.onclick=async()=>{let p='default';try{p=await Notification.requestPermission()}catch{}toast(p==='granted'?'Order updates enabled':'Notifications remain off. Order status stays here.')});
 $$('[data-profile="3"]').forEach(b=>b.onclick=fit);$$('[data-profile]').filter(b=>b.dataset.profile!=='3').forEach(b=>b.onclick=()=>toast('This account section is ready for backend connection'));$$('[data-measure]').forEach(i=>i.oninput=()=>{S.measure[i.dataset.measure]=i.value;save()});$$('[data-save-fit]').forEach(b=>b.onclick=()=>{ok();toast('Measurement profile saved');$('.sheet-backdrop')?.remove()});$$('[data-camera]').forEach(b=>b.onclick=()=>{$('.sheet-backdrop')?.remove();camera()});
 $$('[data-signout]').forEach(b=>b.onclick=()=>{S.auth=false;save();render()});$$('[data-theme]').forEach(b=>b.onclick=()=>{let d=document.documentElement.dataset.forceTheme!=='dark';document.documentElement.dataset.forceTheme=d?'dark':'';document.documentElement.style.colorScheme=d?'dark':'';toast(d?'Dark appearance enabled':'System appearance enabled')});
}
window.addEventListener('online',()=>S.auth&&render());window.addEventListener('offline',()=>S.auth&&render());render();
